#!/usr/bin/env bash
#
# Bundle each 4-file Beamer theme into ONE deployable beamertheme<name>.sty under
# dist/, for low-friction use on Overleaf: import a single file from a raw GitHub
# URL (plus cel_logo.png for the CEL theme) and Refresh it to pull updates.
#
# Keep developing in the four split .sty files (master + color/inner/outer); this
# script regenerates the single-file builds by inlining the color/inner/outer
# bodies into the master at the \useinnertheme/\useoutertheme/\usecolortheme call
# sites and stripping the per-file \mode<presentation>/\mode<all> wrappers.
#
# dist/ is committed so the raw URLs resolve. Re-run after any .sty change
# (scripts/build.sh calls this automatically).
#
# Usage: scripts/bundle.sh
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DIST="${ROOT}/dist"
REPO="https://github.com/chesun/latex_templates"

# Drop the \mode<presentation> / \mode<all> wrapper lines from a source file.
strip_mode() {
  sed -e '/^[[:space:]]*\\mode<presentation>[[:space:]]*$/d' \
      -e '/^[[:space:]]*\\mode<all>[[:space:]]*$/d' "$1"
}

# bundle <srcdir> <name> <distname>
bundle() {
  local srcdir="${ROOT}/$1" name="$2" distname="$3"
  local outdir="${DIST}/${distname}"
  local out="${outdir}/beamertheme${name}.sty"
  mkdir -p "${outdir}"

  local tmpc tmpi tmpo
  tmpc="$(mktemp)"; tmpi="$(mktemp)"; tmpo="$(mktemp)"
  strip_mode "${srcdir}/beamercolortheme${name}.sty" > "${tmpc}"
  strip_mode "${srcdir}/beamerinnertheme${name}.sty" > "${tmpi}"
  strip_mode "${srcdir}/beameroutertheme${name}.sty" > "${tmpo}"

  {
    echo "% beamertheme${name}.sty — single-file build, AUTO-GENERATED by scripts/bundle.sh."
    echo "% Source of truth: ${1}/ in ${REPO}"
    echo "% Do NOT edit here; edit the four split .sty files and re-run scripts/bundle.sh."
    echo "\\mode<presentation>"
    awk -v color="${tmpc}" -v inner="${tmpi}" -v outer="${tmpo}" -v nm="${name}" '
      function dump(f,   l){ while ((getline l < f) > 0) print l; close(f) }
      /^[[:space:]]*\\mode<presentation>[[:space:]]*$/ { next }
      /^[[:space:]]*\\mode<all>[[:space:]]*$/          { next }
      $0 ~ ("\\\\useinnertheme\\{" nm "\\}") { dump(color); dump(inner); dump(outer); next }
      $0 ~ ("\\\\useoutertheme\\{" nm "\\}") { next }
      $0 ~ ("\\\\usecolortheme\\{" nm "\\}") { next }
      { print }
    ' "${srcdir}/beamertheme${name}.sty"
    echo "\\mode<all>"
  } > "${out}"

  rm -f "${tmpc}" "${tmpi}" "${tmpo}"
  echo "    bundled -> dist/${distname}/beamertheme${name}.sty"
}

# Portable in-place sed (works on both BSD/macOS and GNU sed).
sed_inplace() {
  local expr="$1" file="$2" tmp
  tmp="$(mktemp)"
  sed "${expr}" "${file}" > "${tmp}" && mv "${tmp}" "${file}"
}

echo "==> Bundling single-file themes into dist/"
bundle "ucdavis_beamer_theme_xelatex"  "ucdavis" "ucdavis-xelatex"
bundle "ucdavis_beamer_theme_pdflatex" "ucdavis" "ucdavis-pdflatex"
bundle "ca_ed_lab_beamer_theme"        "caedlab" "caedlab"

# CEL needs its logo. On Overleaf both files sit at the project root, so rewrite
# the ../assets/ path to a bare filename and ship the PNG next to the .sty.
sed_inplace 's#\.\./assets/cel_logo\.png#cel_logo.png#g' "${DIST}/caedlab/beamerthemecaedlab.sty"
cp "${ROOT}/assets/cel_logo.png" "${DIST}/caedlab/cel_logo.png"
echo "    copied  -> dist/caedlab/cel_logo.png (logo path rewritten to cel_logo.png)"

echo
echo "Done. dist/ regenerated."
